wamv_camera:
    - name: camera_a
      x: 0.75
      y: -0.3
      P: ${radians(15)}
    - name: camera_b
      x: 0.75
      y: 0.1
      P: ${radians(15)}
wamv_gps:
    - name: gps_wamv
      x: -0.85
wamv_imu:
    - name: imu_wamv
      y: -0.22
wamv_ball_shooter:
    - name: ball_shooter
      x: 0.45
      y: 0.25
      z: 1.3
      pitch: ${radians(-18)}
      yaw: 0
